### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Laky-64** [pytgcalls/pytgcalls#41]
This PyTgCalls roadmap. If you have any requests feel free to leave them here/vote on others.

(There are listed only big change updates)

# 0.0.9 (2021-02-23)

- [x] Removed need of browser
- [x] Added js and ts code compilation
- [x] Kick event listener

# 0.1.0 (2021-03-10)
- [x] Added log mode
- [x] Fixed bugs

# 0.2.0 (2021-03-12)
- [x] Added PyPi installation

# 0.3.0 (2021-03-14)
- [x] Added long timed audio support
- [x] Added closed chat listener
- [x] Added live stream support
- [x] Added support for schema 126

# 0.4.0 (2021-03-25)
- [x] Added invite hash support
- [x] Closing stream when kicked from group
- [x] Added Pulse Stream (Beta)
- [x] Security Fix
- [x] Added the possibility to get max voice chat can start your server
- [x] Customizable cache time of get_full_chat

# 0.6.0 (2021-08-10)
- [x] Support to multilple instance
- [x] Module support
- [x] CustomApi Renewed

# 0.7.0 (2021-08-21)
- [x] STDIN and STDOUT binding to JS instead of use Internal Server
- [x] Custom Exceptions
- [x] Full Async
- [x] Defined Raw Updates 
- [x] Linux ARM64v8 support
- [x] Windows support
- [x] macOS support 
- [x] Pause and Resume result

# 0.8.0 (2021-09-07)
- [x] Pyrogram and Telethon support at same time
- [x] Mute and Unmute
- [x] Video calls support
- [x] Fifo support
- [x] Remote Audio/Video Playing
- [x] Internal FFMPEG Piping
- [x] Image Playing
- [x] Optional Audio Playing
- [x] Get group call participants list
- [x] Decorator when changing partecipants list
- [x] Pre-Made User Agent

# 0.9.0 (2022-05-01)
- [x] Screen sharing (Windows Desktop & Linux Desktop)
- [x] Add UDP Support
- [x] Improvements of the FFMpeg Additional Commands

# No Date Picked
- [x] Add record calls support

**Comment by rojserbest** [comment]
Lol and where is a task to make it non-deaf?

**Comment by nitanmarcel** [comment]
# 0.8.0 (November)
- [ ] Discontinue the project.

**Comment by BlackStoneReborn** [comment]
> # 0.8.0 (November)
> * [ ]  Discontinue the project.

Lmao 🤣
